#!/bin/bash
#
# Run this script to collect debug information regarding state of pods

set -Euox pipefail

BIN=oc
LOGS_DIR="./must-gather"

# Get pods that are not ready and their namespaces
PODS=$(${BIN} get pods --all-namespaces -o jsonpath="{.items[?(@.status.containerStatuses[*].ready==false)].metadata.name}")
NAMESPACES=$(${BIN} get pods --all-namespaces -o jsonpath="{.items[?(@.status.containerStatuses[*].ready==false)].metadata.namespace}")

# Puts pods and corresponding names into arrays
PODS=($PODS)
NAMESPACES=($NAMESPACES)

# Describe and get all pods that are not ready
for index in ${!PODS[@]}; do
    mkdir -p ${LOGS_DIR}/${NAMESPACES[$index]}/${PODS[$index]}
    ${BIN} describe pod ${PODS[$index]} -n ${NAMESPACES[$index]} > ${LOGS_DIR}/${NAMESPACES[$index]}/${PODS[$index]}/describe.log
    ${BIN} get pod ${PODS[$index]} -n ${NAMESPACES[$index]} -o=yaml > ${LOGS_DIR}/${NAMESPACES[$index]}/${PODS[$index]}/get.yaml

done